"""
Mock vLLM server — OpenAI-compatible /v1/chat/completions + /v1/models.

Purpose: let a judge run REPOMIND v3 END-TO-END with NO AMD GPU and NO API keys.
Point VLLM_BASE_URL at this service (compose `mock` profile does it automatically)
and the full SC-TIR agent loop runs locally: it returns a deterministic, valid
SC-TIR response that exercises real tool calls (list_files → read_file → ANSWER).

This is a demo harness ONLY. It does not perform inference; it proves the plumbing.
"""
import time
import uvicorn
from fastapi import FastAPI

app = FastAPI(title="mock-vllm")

# A canned SC-TIR completion: drives one real tool call, then answers.
_SCRIPT = [
    "PLAN: Inspect the repository structure, then read the entry point.\n"
    "CALL: list_files()",
    "THINK: I have the file list. Read the main module to answer the question.\n"
    "CALL: read_file(README.md)",
    "ANSWER: [mock-vLLM] SC-TIR loop executed end-to-end with real tool calls. "
    "In production this response is generated by Qwen3-Coder-Next-FP8 on AMD MI300X "
    "(256K context). This mock proves the full request → route → agent → tools → SSE path "
    "runs locally with no GPU and no API key.",
]


@app.get("/v1/models")
async def models():
    return {"data": [{"id": "Qwen/Qwen3-Coder-Next-FP8", "object": "model",
                      "max_model_len": 262144}]}


@app.post("/v1/chat/completions")
async def chat(payload: dict):
    # Advance the canned script by counting prior ASSISTANT turns (robust even when the
    # analyzed repo itself contains the literal string "OBSERVE:").
    msgs = payload.get("messages", [])
    step = sum(1 for m in msgs if m.get("role") == "assistant")
    content = _SCRIPT[min(step, len(_SCRIPT) - 1)]
    return {
        "id": f"mock-{int(time.time())}",
        "object": "chat.completion",
        "model": payload.get("model", "Qwen/Qwen3-Coder-Next-FP8"),
        "choices": [{"index": 0, "message": {"role": "assistant", "content": content},
                     "finish_reason": "stop"}],
        "usage": {"prompt_tokens": 1000, "completion_tokens": 120, "total_tokens": 1120},
    }


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8080)
